### ISSUE TITLE
Error w.r.t index creation for subject column

### ISSUE THREAD

**Issue by v1p** [kaleidos/grails-direct-messages#3]
Hi, 

Looks like this plugin isn't being maintained anymore, but I gotta say, this is an awesome, easy-to-configure, & pretty comprehensive plugin to manage conversation threads between users, adding the DM functionality just like a charm.

There have been an error w.r.t this plugin, though not causing any trouble with it's use, it's related to index creation for the column subject 

```
Error |
2015-01-19 02:25:28,860 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - Unsuccessful: create index directmessages_message_subject_idx on directmessages_message (subject)

Error |
2015-01-19 02:25:28,876 [localhost-startStop-1] ERROR hbm2ddl.SchemaExport  - BLOB/TEXT column 'subject' used in key specification without a key length
```

It's probably ignorable, still it'll be great to just add the maxSize to the column (perhaps 140 chars is more than enough for subject, or better make it configurable from Config ?) as it can't be overridden otherwise.

**Comment by v1p** [comment]
Please ignore the previous commit, I overlooked the problem. I tried various things, apparently such kind of index creation is not supported from within GORM (i.e. Hibernate).

I tried

```
subject indexColumn:[name:'subject', index:'directmessages_message_subject_idx', type:"text", length: 140]
```

With this, the error goes away, but the index is never created.
Though manually it can be created with key length set to 140.

```
create index directmessages_message_subject_idx on directmessages_message(subject(140))
```

I wonder if It's wise to run this in BootStrap perhaps ?

**Comment by pabloalba** [comment]
Hi!
Thank you, I'm glad you like this plugin.

I'll check the index issue, let's see what can be done :)

**Comment by v1p** [comment]
Thanks a ton @pabloalba

**Comment by pabloalba** [comment]
Hi.

I can't reproduce this error... What version of grails are you using?

Thxs

**Comment by v1p** [comment]
on v 2.2.0 I was getting this error.
The error message doesn't come with 2.4.4 version on grails (to which I am porting to), but the mentioned index is never created.

**Comment by v1p** [comment]
The default index created is this only ;
```
mysql> show index from directmessages_message;
+------------------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table                  | Non_unique | Key_name | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+------------------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| directmessages_message |          0 | PRIMARY  |            1 | id          | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |
+------------------------+------------+----------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
1 row in set (0.00 sec)
```

**Comment by pabloalba** [comment]
It seems to be a mysql problem. On postgresql works fine:
```
messages=# \d directmessages_message
                 Table "public.directmessages_message"
            Column            |            Type             | Modifiers 
------------------------------+-----------------------------+-----------
 id                           | bigint                      | not null
 version                      | bigint                      | not null
 date_created                 | timestamp without time zone | not null
 from_deleted_on_thread       | boolean                     | 
 from_id                      | bigint                      | not null
 from_name                    | character varying(255)      | 
 last                         | boolean                     | not null
 last_on_thread               | boolean                     | 
 number_of_messages_on_thread | integer                     | 
 readed                       | boolean                     | not null
 reply                        | boolean                     | 
 subject                      | text                        | 
 text                         | text                        | not null
 to_deleted_on_thread         | boolean                     | 
 to_id                        | bigint                      | not null
 to_name                      | character varying(255)      | 
Indexes:
    "directmessages_message_pkey" PRIMARY KEY, btree (id)
    "directmessages_message_subject_idx" btree (subject) 
```

There is a lot of questions about this on stackoverflow (like http://stackoverflow.com/questions/23904429/use-hibernate-jpa-mysql-database-create-index-error), but it seems like an incompability between hibernate and mysql indexes on blob.

So, I don't like the idea of create the index on bootstrap, because it is an issue only for mysql, and I prefer to maintain the standard way... I think it is better to do it on the bootstrap of the real application that uses mysql. I'll made a note on the documentation.

**Comment by v1p** [comment]
Alright thanks a ton, It's better to handle it at database level it seems, since on production schema creation typically happens once.
